const fs=require('fs'),path=require('path'),assert=require('assert');const {JSDOM}=require(process.env.JSDOM_PATH||'jsdom');const root=path.resolve(__dirname,'..'),routes=JSON.parse(fs.readFileSync(root+'/brief/routes.json'));const data=JSON.parse(fs.readFileSync(root+'/content.json'));let checkedLinks=0;const errors=[],tests=[];
function ok(name,fn){try{fn();tests.push({name,passed:true})}catch(e){tests.push({name,passed:false,error:e.message});errors.push(name+': '+e.message)}}
ok('480 routes; 160 per locale',()=>{assert.equal(routes.length,480);for(const l of ['nl','en','id'])assert.equal(routes.filter(r=>r.lang===l).length,160)});
for(const r of routes){const file=path.join(root,r.file),html=fs.readFileSync(file,'utf8');const dom=new JSDOM(html),doc=dom.window.document;
 if(!doc.querySelector('h1'))errors.push(r.file+': missing h1');if(doc.documentElement.lang!==r.lang)errors.push(r.file+': wrong lang');
 if(/\{\{RESEARCH_LINK\}\}|\[object Object\]|undefined|3× Master|3× Gelar/.test(html))errors.push(r.file+': unresolved or stale content');
 for(const el of doc.querySelectorAll('[src],[href],[poster],[data-src]'))for(const k of ['src','href','poster','data-src']){let v=el.getAttribute(k);if(!v||v.startsWith('#')||/^(https?:|mailto:|tel:|data:)/.test(v))continue;v=decodeURIComponent(v.split(/[?#]/)[0]);if(!fs.existsSync(path.resolve(path.dirname(file),v)))errors.push(r.file+': missing '+v);checkedLinks++}
 const ids=[...doc.querySelectorAll('[id]')].map(x=>x.id);if(new Set(ids).size!==ids.length)errors.push(r.file+': duplicate IDs');
 for(const im of doc.querySelectorAll('img'))if(!im.hasAttribute('alt'))errors.push(r.file+': missing alt');dom.window.close();}
tests.push({name:'All HTML local links, sources, posters and image alt attributes',passed:!errors.length,checkedLinks});
function runtime(file){const dom=new JSDOM(fs.readFileSync(root+'/'+file,'utf8'),{url:'https://preview.example/'+file,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.matchMedia=()=>({matches:false,addEventListener(){}});w.scrollTo=()=>{};w.HTMLElement.prototype.scrollTo=()=>{};w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','')};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open')};w.eval(fs.readFileSync(root+'/assets/site.js','utf8'));w.eval(fs.readFileSync(root+'/assets/revision.js','utf8'));w.eval(fs.readFileSync(root+'/assets/polish.js','utf8'));return dom}
ok('Theme and menu keyboard state',()=>{const d=runtime('en/index.html'),w=d.window,q=s=>w.document.querySelector(s);q('.theme-toggle').click();assert.equal(w.document.documentElement.dataset.theme,'dark');assert.equal(w.localStorage.getItem('eggan-theme'),'dark');q('.theme-toggle').click();assert.equal(w.document.documentElement.dataset.theme,'light');q('.menu-toggle').click();assert(q('#menu-dialog').open);q('#menu-dialog [data-close]').click();assert(!q('#menu-dialog').open);q('.motion-toggle').click();assert.equal(w.document.documentElement.dataset.motion,'off');d.window.close()});
ok('Archive all 129 media, 79 image / 50 video and filter state',()=>{const d=runtime('en/creative-work/index.html'),q=s=>d.window.document.querySelector(s),all=s=>[...d.window.document.querySelectorAll(s)];assert.equal(all('.media-card').length,129);assert.equal(all('.media-card').filter(e=>!e.hidden).length,20);q('[data-filter=video]').click();assert.equal(all('.media-card').filter(e=>!e.hidden).length,20);q('#load-more').click();q('#load-more').click();assert.equal(all('.media-card').filter(e=>!e.hidden).length,50);assert(q('#load-more').hidden);q('[data-filter=image]').click();assert.equal(all('.media-card').filter(e=>!e.hidden).length,20);while(!q('#load-more').hidden)q('#load-more').click();assert.equal(all('.media-card').filter(e=>!e.hidden).length,79);q('[data-filter=all]').click();while(!q('#load-more').hidden)q('#load-more').click();assert.equal(all('.media-card').filter(e=>!e.hidden).length,129);d.window.close()});
for(const r of data.RESEARCH)ok('Reader bounds, thumbnail, zoom and persistence: '+r.slug,()=>{const d=runtime('en/research/'+r.slug+'/index.html'),q=s=>d.window.document.querySelector(s),w=d.window;assert(q('[data-page-step="-1"]').disabled);q('[data-page-step="1"]').click();assert.equal(q('.page-input').value,'2');q(`[data-page="${r.pages}"]`).click();assert(q('[data-page-step="1"]').disabled);q('.page-input').value='999';q('.page-input').dispatchEvent(new w.Event('change'));assert.equal(q('.page-input').value,String(r.pages));q('#zoom-page').click();assert(q('.reader-viewport').classList.contains('zoomed'));assert.equal(w.localStorage.getItem('eggan-reader-'+r.slug),String(r.pages));d.window.close()});
ok('No people/photo images on leadership index or field cover',()=>{const d=new JSDOM(fs.readFileSync(root+'/en/leadership/index.html'));assert.equal(d.window.document.querySelectorAll('main img').length,0);d.window.close()});
ok('Original photo lightbox opens, navigates, zooms and closes',()=>{const d=runtime('en/leadership/unesco-undp/index.html'),q=s=>d.window.document.querySelector(s);q('.zoomable').click();assert(q('#image-dialog').open);assert(q('#lightbox-image').src.includes('unesco-undp-1.jpg'));q('#image-next').click();assert(q('#lightbox-image').src.includes('unesco-undp-2.jpg'));q('#image-zoom').click();assert(q('.lightbox-stage').classList.contains('zoomed'));q('#image-dialog [data-close]').click();assert(!q('#image-dialog').open);d.window.close()});
ok('Thesis language updates preview and download together',()=>{const d=runtime('en/documents/thesis/index.html'),q=s=>d.window.document.querySelector(s);q('#doc-language').selectedIndex=1;q('#doc-language').dispatchEvent(new d.window.Event('change'));assert(q('.doc-preview').href.endsWith('master-thesis-indonesian.pdf'));assert.equal(q('.doc-preview').href,q('.doc-download').href);assert(q('.document-page-image').src.endsWith('thesis-id-01.jpg'));assert.equal(q('#document-page-total').textContent,'275');q('[data-doc-step="1"]').click();assert(q('.document-page-image').src.endsWith('thesis-id-02.jpg'));q('[data-doc-page="275"]').click();assert(q('[data-doc-step="1"]').disabled);q('[data-document-language=en]').click();assert.equal(q('#document-page-total').textContent,'256');assert(q('.doc-preview').href.endsWith('master-thesis-english.pdf'));d.window.close()});
ok('98 public research page images present',()=>assert.equal(data.RESEARCH.reduce((n,r)=>n+fs.readdirSync(root+'/assets/research/'+r.slug).filter(x=>x.endsWith('.jpg')).length,0),98));
ok('All creative media bundled locally',()=>data.SHOWCASE.forEach(s=>{for(const k of ['file','poster']){assert(s[k].startsWith('/assets/'));assert(fs.statSync(root+s[k]).size>100)}}));
ok('No generated Critical Grounds event media bundled',()=>{assert(!fs.existsSync(root+'/assets/gallery/critical-grounds-stage.jpg'));assert(!fs.existsSync(root+'/assets/leadership/biru-muda.jpg'))});

for(const p of data.PROJECTS)ok('Product gallery thumbnails, wraparound, image viewer: '+p.slug,()=>{const d=runtime('en/work/'+p.slug+'/index.html'),w=d.window,q=s=>w.document.querySelector(s),all=s=>[...w.document.querySelectorAll(s)];const count=all('[data-slide]').length;assert(count>1);q('[data-slide-step="1"]').click();assert.equal(q('[data-slide="1"]').getAttribute('aria-pressed'),'true');const href=q('.project-slide').href;assert.equal(q('#project-main-image').src,href);q('.project-slide').click();assert(q('#image-dialog').open);assert.equal(q('#lightbox-image').src,href);q('#image-dialog [data-close]').click();q('[data-slide="0"]').click();q('[data-slide-step="-1"]').click();assert.equal(q('#slide-count').textContent,String(count).padStart(2,'0')+' / '+String(count).padStart(2,'0'));d.window.close()});
ok('Research status filters all four statuses',()=>{const d=runtime('en/research/index.html'),q=s=>d.window.document.querySelector(s),rows=[...d.window.document.querySelectorAll('.research-row')];for(const status of ['published','ongoing','proposal','submitted']){q('[data-research-filter='+status+']').click();assert.equal(rows.filter(x=>!x.hidden).length,1);assert.equal(rows.find(x=>!x.hidden).dataset.status,status)}q('[data-research-filter=all]').click();assert.equal(rows.filter(x=>!x.hidden).length,4);d.window.close()});
ok('Home has all six reference scenes and original portrait',()=>{const d=runtime('en/index.html'),q=s=>d.window.document.querySelector(s);for(const s of ['.opening-scroll','.journey-scroll','.systems-stage','.creative-stage','.home-research','.people-stage','.talk-strip'])assert(q(s),s);assert(q('.opening-portrait img').src.includes('profile-nobg.png'));assert.equal(d.window.document.querySelectorAll('.product-monument').length,3);d.window.close()});
ok('All locale menus expose eight main destinations',()=>{for(const prefix of ['en/','id/','']){const d=runtime(prefix+'index.html');assert.equal(d.window.document.querySelectorAll('.menu-inner nav a').length,8);d.window.close()}});

ok('Document page image counts match original PDF manifest',()=>{const pages=JSON.parse(fs.readFileSync(root+'/assets/credentials/document-pages.json'));for(const [key,m] of Object.entries(pages))assert.equal(fs.readdirSync(root+'/assets/credentials/pages/'+key).filter(n=>n.endsWith('.jpg')).length,m.pages)});
const report={date:new Date().toISOString(),htmlPages:routes.length,checkedLinks,tests,errors,browserVisualQA:JSON.parse(fs.readFileSync(root+'/brief/browser-verification.json','utf8'))};fs.writeFileSync(root+'/brief/verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({pages:routes.length,checkedLinks,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,errors:errors.slice(0,25)},null,2));if(errors.length)process.exitCode=1;
